# Generated by Django 3.1.6 on 2021-05-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=6)),
                ('Field', models.CharField(max_length=3)),
            ],
        ),
    ]
