# Generated by Django 3.1.6 on 2021-05-08 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FMS', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='Forms',
        ),
    ]
